#!/bin/bash

trap "exit 0" SIGTERM

if [ -x /etc/mergerfsp/array_start.sh ]; then

    TIMER=0

    while [ ! -d /mnt/user ]; do
        sleep 1
        TIMER=$((TIMER+1))
        if [ $TIMER -ge 20 ]; then
            break
        fi
    done

    if [ -d /mnt/user ]; then
        echo "Executing mergerFS array start script (disks_mounted)..." | logger
        /etc/mergerfsp/array_start.sh 2>&1 | logger
    else
        echo "mergerFS warning: /mnt/user never became available (within a 20 seconds timeout)." | logger
        echo "mergerFS warning: The mergerFS array start script has therefore not been executed." | logger
    fi

fi
