#!/bin/bash
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright desertwitch
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
CONFIG="/boot/config/plugins/mergerfsp/mergerfsp.cfg"
[ -e "$CONFIG" ] && source $CONFIG

TIMERSTOPKILL=$((TIMERSTOP+10))

if [ -x /etc/mergerfsp/array_stop_complete.sh ]; then
    echo "mergerFS -- array_stop_complete.sh is now executing (event: stopped, timeout: ${TIMERSTOP}s)..." | logger -t "mergerfs-plugin"

    timeout "--kill-after=$TIMERSTOPKILL" "$TIMERSTOP" /etc/mergerfsp/array_stop_complete.sh 2>&1 | logger -t "array_stop_complete.sh"
    CMDRET="${PIPESTATUS[0]}"

    if [ "$CMDRET" -eq 124 ]; then
        echo "mergerFS error -- array_stop_complete.sh has timed out after ${TIMERSTOP}s and was stopped with SIGTERM." | logger -t "mergerfs-plugin"
    elif [ "$CMDRET" -eq 137 ]; then
        echo "mergerFS error -- array_stop_complete.sh has timed out after ${TIMERSTOP}s, ignored SIGTERM and was killed with SIGKILL." | logger -t "mergerfs-plugin"
    elif [ ! "$CMDRET" -eq 0 ]; then
        echo "mergerFS error -- array_stop_complete.sh has returned with a non-zero exit code ($CMDRET)." | logger -t "mergerfs-plugin"
    else
        echo "mergerFS -- array_stop_complete.sh has been executed with success." | logger -t "mergerfs-plugin"
    fi
fi
